# -*- coding: utf-8 -*-
"""modelbuilding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVDjF0aZb0U7pRXTBGL5qK7019QIIZzq
"""

import pandas as pd

df = pd.read_csv("/content/Salary Data.csv")

df

df.isnull().sum()

for column in df.columns:
    if df[column].dtype in ['int64', 'float64']:
        df[column].fillna(df[column].mean(), inplace=True)
    else:
        df[column].fillna(df[column].mode()[0], inplace=True)
df.isnull().sum()

df.drop_duplicates(inplace=True)
df.shape

df

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

for column in ['Gender', 'Education Level', 'Job Title']:
    if column in df.columns:
        df[column] = label_encoder.fit_transform(df[column])

df.head()

X = df.drop('Salary', axis=1)
y = df['Salary']

print("Input features (X) shape:", X.shape)
print("Target variable (y) shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""### Training various Machine Learning Models"""

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

# Initialize models
models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'K-Nearest Neighbors': KNeighborsRegressor(),
    'Support Vector Machine': SVR()
}

# Train and predict for each model
predictions = {}
for name, model in models.items():
    print(f"Training {name}...")
    model.fit(X_train, y_train)
    predictions[name] = model.predict(X_test)
    print(f"Finished training {name}.")

for name, pred in predictions.items():
    print(f"\nPredictions for {name}:")
    print(pred[:5]) # Display first 5 predictions

"""### Model Evaluation"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


# Evaluate each model
evaluation_results = {}
for name, pred in predictions.items():
    mae = mean_absolute_error(y_test, pred)
    mse = mean_squared_error(y_test, pred)
    r2 = r2_score(y_test, pred)

    evaluation_results[name] = {
        'MAE': mae,
        'MSE': mse,
        'R2 Score': r2
    }

# Display evaluation results
for name, metrics in evaluation_results.items():
    print(f"\n--- {name} Evaluation ---")
    for metric_name, value in metrics.items():
        print(f"{metric_name}: {value:.2f}")

import matplotlib.pyplot as plt
import numpy as np

# Prepare data for plotting
model_names = list(evaluation_results.keys())
r2_scores = [metrics['R2 Score'] for metrics in evaluation_results.values()]
mae_scores = [metrics['MAE'] for metrics in evaluation_results.values()]
mse_scores = [metrics['MSE'] for metrics in evaluation_results.values()]

x = np.arange(len(model_names))
width = 0.25

fig, ax1 = plt.subplots(figsize=(12, 7))

# Plot R2 Scores
rects1 = ax1.bar(x - width, r2_scores, width, label='R2 Score', color='skyblue')
ax1.set_xlabel('Models')
ax1.set_ylabel('R2 Score', color='skyblue')
ax1.set_title('Model Performance Comparison')
ax1.set_xticks(x)
ax1.set_xticklabels(model_names, rotation=45, ha="right")
ax1.tick_params(axis='y', labelcolor='skyblue')
ax1.set_ylim(-0.2, 1.0) # Adjust y-limit for R2 score

# Create a second y-axis for MAE (or MSE if preferred, adjust accordingly)
ax2 = ax1.twinx()
rects2 = ax2.bar(x, mae_scores, width, label='MAE', color='lightcoral')
ax2.set_ylabel('Mean Absolute Error (MAE)', color='lightcoral')
ax2.tick_params(axis='y', labelcolor='lightcoral')

# Function to add labels on top of bars
def autolabel(rects, ax, offset_y=5):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.2f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, offset_y), # 3 points vertical offset
                    textcoords="offset points",
                    ha='center', va='bottom')

# Add labels to bars
autolabel(rects1, ax1, offset_y=10)
autolabel(rects2, ax2, offset_y=10)

fig.tight_layout()
plt.legend(loc='upper left')
plt.show()

"""### Visualizing Model Predictions (Actual vs. Predicted)"""

import matplotlib.pyplot as plt
import seaborn as sns

# Choose the best performing model (e.g., Random Forest based on previous evaluation)
best_model_name = 'Random Forest'
actual_salaries = y_test
predicted_salaries = predictions[best_model_name]

plt.figure(figsize=(10, 7))
sns.scatterplot(x=actual_salaries, y=predicted_salaries, alpha=0.6)
plt.plot([actual_salaries.min(), actual_salaries.max()],
         [actual_salaries.min(), actual_salaries.max()],
         'r--', lw=2, label='Perfect Prediction Line')
plt.xlabel('Actual Salaries')
plt.ylabel('Predicted Salaries')
plt.title(f'Actual vs. Predicted Salaries for {best_model_name}')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Choose the SVM model
best_model_name = 'Support Vector Machine'
actual_salaries = y_test
predicted_salaries = predictions[best_model_name]

plt.figure(figsize=(10, 7))
sns.scatterplot(x=actual_salaries, y=predicted_salaries, alpha=0.6)
plt.plot([actual_salaries.min(), actual_salaries.max()],
         [actual_salaries.min(), actual_salaries.max()],
         'r--', lw=2, label='Perfect Prediction Line')
plt.xlabel('Actual Salaries')
plt.ylabel('Predicted Salaries')
plt.title(f'Actual vs. Predicted Salaries for {best_model_name}')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

print("\n--- Model Performance Comparison ---")
for name, metrics in evaluation_results.items():
    print(f"\n{name}:")
    for metric_name, value in metrics.items():
        print(f"  {metric_name}: {value:.2f}")

"""### Saving the Best Model"""

import pickle

best_model_name = 'Random Forest'
best_model = models[best_model_name]

# Save the best model to a .pkl file
filename = f'{best_model_name.replace(" ", "_").lower()}_model.pkl'
pickle.dump(best_model, open(filename, 'wb'))

print(f"Best model ('{best_model_name}') saved as '{filename}'")